markdown: rdiscount
pygments: true
baseurl: /
permalink: /:title
rdiscount:
  extensions: [smart]
title : bob in air 
production_url : nickl1.github.io
description: "tech fan"
disqus_shortname: jekyllchenbo 
author :
  name : air_bob 
  github : airbob
  twitter : air_bob
  email: air.chenbo@gmail.com
